### PR TITLE
Custom naming options

### PR DESCRIPTION
**Pull request by outring**
We're using non-standard BEM classes naming scheme in our project, so I've added support for custom naming options.

### CODE REVIEW

**Comment by dfilatov** [comment]
I would prefer to add ability to specify function which accepts "block", "elem", "mods" and builds final bem-like name . It's more flexible than specifying just delemiters.

**Comment by tadatuta** [comment]
don't you want to use https://github.com/bem/bem-naming ?

**Comment by outring** [comment]
@dfilatov Maybe, but I can't remember or imagine any different scheme other than scheme with different delimiters. Such implementation will just add more complexity to end users.
@tadatuta Haven't heard about it. Seems to be a great thing. And it has similar [custom naming options](https://github.com/bem/bem-naming#custom-naming-convention) too, btw.

**Comment by outring** [comment]
@dfilatov what if I just simplify options to be compliant with [bem-naming](https://github.com/bem/bem-naming) (i.e. remove modValDelim)?

**Comment by dfilatov** [comment]
I still prefer to have ability to specify function as the most flexible solution without any additional dependencies.

**Comment by outring** [comment]
Possible real BEM-world usages of such function?

**Comment by dfilatov** [comment]
For instance, if I'll want to have following representation in className: `block _modName1_modVal1 _modName2_modVal2`.

**Comment by outring** [comment]
So you talking about function for generating all entity classes (including mixins), i.e. replacement of [buildBemClassName](https://github.com/dfilatov/bem-react/blob/master/lib/buildBemClassName.js). As for me it's totally different option and could be (and probably should be) implemented separately.

Well, I'll just continue to use fork. Thanks.

**Comment by dfilatov** [comment]
I don't see where it could be used except as for building className.

**Pull request closed without merging**
